/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MessageBox: typeof import('./src/components/MessageBox.vue')['default']
    MessageButton: typeof import('./src/components/MessageButton.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageLoading: typeof import('./src/components/MessageLoading.vue')['default']
    MessageTile: typeof import('./src/components/MessageTile.vue')['default']
    RegionComponent: typeof import('./src/components/RegionComponent.vue')['default']
    RiskfactorCheckbox: typeof import('./src/components/RiskfactorCheckbox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
